name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # 소스코드의 테스트를 진행하는 Job
  build:
    # 이 Job 은 Ubuntu 최신 LTS 에서 실행한다.
    runs-on: ubuntu-latest
    # 이 Job 의 개별 단계
    steps:
      # 소스코드 가져오기
      - name: Checkout source
        uses: actions/checkout@v4
      # JDK 설치하기
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        # Action 에 전달할 인자들
        with:
          java-version: '17'
          distribution: 'temurin'

      # Gradle 설정하기
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3.1.0

      # Gradle Wrapper 로  Test 진행
      - name: Test with Gradle Wrapper
        run: ./gradlew test
