name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3.1.0
      # Gradle 실행 권한 부여
      - name: Grant execute permission for Gradle Wrapper
        run: chmod +x ./gradlew
      - name: Test with Gradle Wrapper
        run: ./gradlew test

  # 서로 다른 Job 은 서로 다른 컴퓨터에서 실행한다고 가정하고
  # 작성해주자
  boot-jar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3.1.0
      # Gradle Wrapper 로 JAR 파일 생성
      - name: Create Boot JAR with Gradle Wrapper
        run: ./gradlew bootJar
      # JAR 파일을 Artifact 로 업로드
      - name: Upload JAR
        uses: actions/upload-artifact@v4
        # 어떤 파일을 업로드 할건지
        with:
          name: artifact
          path: build/libs/*.jar
